baseURL = "https://shoya.io/"
languageCode = "en-us"
title = "shoya.io"

DefaultContentLanguage = "en"
[Languages]
  [Languages.en]
    [Languages.en.params.navigation]
      projects = "Projects"
      publications = "Publications"
      software = "Software"
      posts = "Posts"
      language = "English page"
  [Languages.jp]
    [Languages.jp.params.navigation]
      projects = "プロジェクト"
      publications = "論文"
      software = "ソフトウェア"
      posts = "ブログ"
      language = "日本語のページ"

[frontmatter]
date  = [":filename", ":default"]